using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using EPMPolicyBuilder.Models;

namespace EPMPolicyBuilder.ViewModels;

public partial class RuleBuilderViewModel : ObservableObject
{
    // Tracks the last auto-generated name so manual edits are not overwritten.
    private string _autoGeneratedName = string.Empty;

    [ObservableProperty] private string _ruleName = string.Empty;
    [ObservableProperty] private string _ruleDescription = string.Empty;
    [ObservableProperty] private int _elevationTypeIndex;
    [ObservableProperty] private int _childProcessBehaviorIndex;
    [ObservableProperty] private int _signatureSourceIndex;
    [ObservableProperty] private bool _validationBusinessJustification;
    [ObservableProperty] private bool _validationWindowsAuthentication;
    [ObservableProperty] private bool _showValidationOptions;
    [ObservableProperty] private bool _showReusableCertComboBox;
    [ObservableProperty] private bool _showUploadCertButton;
    [ObservableProperty] private string _uploadedCertPath = string.Empty;
    [ObservableProperty] private ReusableSetting? _selectedReusableCert;
    [ObservableProperty] private FileMetadata? _fileMetadata;
    // Detected cert info (read-only display)
    [ObservableProperty] private string _detectedCertSubject = string.Empty;
    [ObservableProperty] private string _detectedCertThumbprint = string.Empty;
    [ObservableProperty] private string _detectedCertValidTo = string.Empty;
    [ObservableProperty] private bool _hasDetectedCert;

    public ObservableCollection<ReusableSetting> ReusableCertificates { get; } = [];
    public ObservableCollection<string> ElevationTypes { get; } = ["User Confirmed", "Automatic", "Deny", "Support Approved", "Elevate As Current User"];
    public ObservableCollection<string> ChildProcessBehaviors { get; } = ["Require rule to elevate", "Deny all", "Allow child processes to run elevated"];
    public ObservableCollection<string> SignatureSources { get; } = ["Not Configured", "Reusable Certificate", "Upload Certificate"];

    partial void OnElevationTypeIndexChanged(int value)
    {
        ShowValidationOptions = value == 0 || value == 4; // UserConfirmed or ElevateAsCurrentUser
    }

    partial void OnSignatureSourceIndexChanged(int value)
    {
        ShowReusableCertComboBox = value == 1;
        ShowUploadCertButton = value == 2;
    }

    public ElevationRule BuildRule()
    {
        return new ElevationRule
        {
            RuleName = RuleName,
            RuleDescription = RuleDescription,
            ElevationType = (ElevationType)ElevationTypeIndex,
            ChildProcessBehavior = (ChildProcessBehavior)ChildProcessBehaviorIndex,
            SignatureSource = (SignatureSource)SignatureSourceIndex,
            ReusableCertificateId = SelectedReusableCert?.Id,
            UploadedCertificatePath = UploadedCertPath,
            ValidationBusinessJustification = ValidationBusinessJustification,
            ValidationWindowsAuthentication = ValidationWindowsAuthentication,
            FileMetadata = FileMetadata
        };
    }

    public void SetFileMetadata(FileMetadata? metadata)
    {
        FileMetadata = metadata;
        ApplyDefaultRuleName(metadata);
        ApplyDetectedCert(metadata);
    }

    private void ApplyDetectedCert(FileMetadata? metadata)
    {
        if (metadata == null || !metadata.HasDetectedCert)
        {
            HasDetectedCert = false;
            DetectedCertSubject = string.Empty;
            DetectedCertThumbprint = string.Empty;
            DetectedCertValidTo = string.Empty;
            return;
        }

        HasDetectedCert = true;
        // Show a clean common name rather than the full DN.
        DetectedCertSubject = ExtractCN(metadata.CertSubject) is { Length: > 0 } cn
            ? cn : metadata.CertSubject;
        DetectedCertThumbprint = metadata.CertThumbprint;
        DetectedCertValidTo = metadata.CertValidTo.HasValue
            ? metadata.CertValidTo.Value.ToLocalTime().ToString("yyyy-MM-dd")
            : string.Empty;

        // Pre-select "Upload Certificate" and point at the exported .cer so the
        // admin doesn't have to browse manually.
        if (!string.IsNullOrWhiteSpace(metadata.DetectedCertPath))
        {
            UploadedCertPath = metadata.DetectedCertPath;
            SignatureSourceIndex = 2; // "Upload Certificate"
        }
    }

    private static string ExtractCN(string dn)
    {
        // Parse CN= from a Distinguished Name like "CN=Microsoft Corporation, O=..."
        foreach (var part in dn.Split(','))
        {
            var trimmed = part.Trim();
            if (trimmed.StartsWith("CN=", StringComparison.OrdinalIgnoreCase))
                return trimmed[3..].Trim();
        }
        return string.Empty;
    }

    private void ApplyDefaultRuleName(FileMetadata? metadata)
    {
        string generated = BuildDefaultName(metadata);
        // Only overwrite if the admin hasn't changed from the last auto-generated value.
        if (string.IsNullOrWhiteSpace(RuleName) || RuleName == _autoGeneratedName)
        {
            _autoGeneratedName = generated;
            RuleName = generated;
        }
    }

    private static string BuildDefaultName(FileMetadata? metadata)
    {
        if (metadata == null) return "EPM Elevation Rule";

        // Prefer ProductName, fall back to FileName without extension.
        string appLabel = !string.IsNullOrWhiteSpace(metadata.ProductName)
            ? metadata.ProductName
            : System.IO.Path.GetFileNameWithoutExtension(metadata.FileName);

        string version = !string.IsNullOrWhiteSpace(metadata.FileVersion)
            ? $" {metadata.FileVersion}"
            : string.Empty;

        return $"Elevate {appLabel}{version}";
    }
    public void SetReusableCertificates(IEnumerable<ReusableSetting> certs)
    {
        ReusableCertificates.Clear();
        foreach (var c in certs) ReusableCertificates.Add(c);
    }
}
